spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      local: true
      repositories:
        enabled: true
es-query:
  hostname: "localhost"
  port: 9200